name: jenn
channels:
- conda-forge
- defaults
dependencies:
- numpy  # for neural computations
- matplotlib  # for goodness of fit
- jupyterlab  # for examples
- twine  # for packaging
- build  # for packaging
- pip
- pip:
    - -r requirements.txt
