name: jenn-dev
channels:
- conda-forge
- defaults
dependencies:
- numpy  # for neural computations
- matplotlib  # for goodness of fit
- jupyterlab  # for examples
- pytest  # for unit testing
- pip
- pip:
    - -r requirements.txt
